# Generated by Django 5.1.15 on 2026-05-01 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('role_changed', 'Role Changed')], max_length=20)),
                ('scope_type', models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project')], max_length=10)),
                ('scope_id', models.UUIDField()),
                ('old_role', models.CharField(blank=True, default='', max_length=10)),
                ('new_role', models.CharField(blank=True, default='', max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='membership__scope_t_be74a1_idx'), models.Index(fields=['target_user'], name='membership__target__a247a3_idx')],
            },
        ),
    ]
